### ISSUE TITLE
1.21 Tracking

### ISSUE THREAD

**Issue by Machine-Maker** [PaperMC/Paper#10876]
To do list, roughly in order of importance

- [x] verify all dispensers correctly shrink stack only 1 time
- [x] `disableTeleportationSuffocationCheck` no longer needed, no collision check in PlayerList#respawn
- [x] Revisit portal logic on end gateways (Cooldown on EndGateway no longer cancellable by PortalEvent) https://github.com/PaperMC/Paper/pull/10892
- [x] Mace Knockback logic for respective events
- [x] Test ShaplessRecipe ExactChoice
- [x] https://github.com/PaperMC/Paper/pull/12835
- [x] Expose world spawn angle patch
- [x] Check on fix DamageSource API (specifically, BlockAttachedEntity hurt)
- [x] unsafe end portal teleportation patch still needed? ~~ (owen) Don't think so, MC fixed underlying issue.
- [x] Ensure book disconnect called on main is redundant?
- [x] ~~Any possibility of keeping EntityPortalReadyEvent#setTargetWorld?~~ Yep, kept it working
- [x] Discuss removal of PlayerItemMendEvent's IntUnary durability -> xp (potentially keep consumedXp)
- [ ] Check on upstreams AttributeModifier#getUUID logic (its terrible): https://github.com/PaperMC/Paper/issues/11015
- [x] Forward https://github.com/PaperMC/Paper/pull/10880
- [x] Check in on BlockData#getDestroySpeed
- [x] Fix enchantWIthLevels treasureOnly boolean
- [x] Forward https://github.com/PaperMC/Paper/pull/10886
- [ ] Test WitherBoss can portal API
- [x] Test "Fix block place logic"'s Jukebox (This is now handled on JukeboxBlock, no server logic runs beyond interact event)
- [x] Test leashes and respective events
- [x] `Done (Xs)!` message shows wrong time
- [ ] Investigate if "Fix entity tracker desync when new players are added to the  tracker" is still needed
- [x] Recheck Experimental Annotations
- [x] test mass craft perf improvement w/spark
- [ ] Revisit https://github.com/PaperMC/Paper/commit/7bbe6820c24cf3f8c7ec521a0712184c67816343 before stable
- [x] Check in on alternate-current (https://github.com/SpaceWalkerRS/alternate-current/commit/eb405af873e75185f7fde581c2237d2b2b249f41#diff-087eb51f8c173a688076fe844b5cd6529953aea995e9ae6a7230fda2d3c44d60L1063-R1063)
