### ISSUE TITLE
Chat Tab Complete - Misc. Issues Tracking

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paper#1429]
In 1.13 builds there's been lots of changes to how tab completion works and our own code in that area. This is just a general tracking ticket for some of the odds and ends stuff that has come up in discussion around this area.

- [ ] Paper-API adds an AsyncTabComplete event which we believe is functioning properly but needs to be tested to make sure it works as expected with plugins from the 1.12.2 era.

- [x] We've re-added the  synchronous TabCompleteEvent but we removed where it was fired in one of our fix commits, so we need to look at getting that firing again.

- [x] Just generally this area (_PlayerConnection#a(PacketPlayInTabComplete)_) is starting to get messy and could use another look around for cleanup.

The brigadier API library is imported and available to modify if needed (as came up in discussion); see importmcdev.sh for instructions on how to do that.

**Comment by electronicboy** [comment]
2 and 3 have been done for a few days, 1 could do with somebody testing properly, but I'm not aware of any plugins using this event, and my own test plugin worked as intended in 1.13

**Comment by zachbr** [comment]
I believe ACF uses it so perhaps we could find some plugins made with ACF for testing?

**Comment by aikar** [comment]
my own uses it, I'll let you know what's status.

**Comment by aikar** [comment]
ok something is broken, tab complete not working at all. leave it open and ill see if i can figure it out.

**Comment by Chew** [comment]
Going to assume y'all got this all good. Thanks for all your hard work ❤️

**Comment by Qboi123** [comment]
By me it's not working... The event is not fired at all. The other events in the same class are just firing.

**Comment by electronicboy** [comment]
chat itself no longer tab completes, only commands, and commands must be registered in the server and sent to the client to work properly; if there is an issue, please create a new ticket instead of bumping closed/outdated issues
