### ISSUE TITLE
Paper 1.9 Update TODO

### ISSUE THREAD

**Issue by zachbr** [PaperMC/Paper#29]
1.9 cleanup and organization changes:
- [x] Drop "Spigot" from all "PaperSpigot" patch notes and ... everything
- [x] Return the proper implementation name (ie private final String serverName = "CraftBukkit")
- [x] Cleanup and organize build scripts (own folder?)
- [x] Setup Bukkit-Patches and CraftBukkit-Patches as a single Spigot submodule, rather than true dirs we maintain.
- [x] Refactor Paper packages
- [x] Move our API stuff out of Class.spigot(), we're done with that.

**Comment by aikar** [comment]
- [ ] Slow loading libs - need to investigate if this still has value to do
  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/7d15d07c929caae6454ae2cd7197cb86b0582a16#CraftBukkit-Patches/0128-Fix-Slow-Loading-Libraries.patch
- [x] Chunk save thread, super important to add back
  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/7d15d07c929caae6454ae2cd7197cb86b0582a16#CraftBukkit-Patches/0160-Don-t-sleep-between-chunk-saves.patch
- [ ] Investigate if this is also still beneficial (potentially not)
  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/7d15d07c929caae6454ae2cd7197cb86b0582a16#CraftBukkit-Patches/0062-More-Efficient-GetCubes.patch
- [ ] Investigate DataWatcher optimizations patch
  https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/7d15d07c929caae6454ae2cd7197cb86b0582a16#CraftBukkit-Patches/0053-Optimize-DataWatcher.patch

**Comment by NoChanceSD** [comment]
Would be nice to keep the anti xray feature as well. 
It might hurt performance but it has been very useful to me and i'm sure other people would like it the same.

**Comment by McLive** [comment]
:+1: I'd also like to see anti xray

**Comment by zachbr** [comment]
@McLive @NoChanceSD
I've removed your comments about anti-xray as I feel that should be a separate issue from this one.
Also, it's very unlikely we'll find a pleasant way to bring it back, and if we did we'd want to get it back up to Spigot ASAP anyway.
