### ISSUE TITLE
Component Support Tracking Issue

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/Paper#3715]
This issue should track the progress on exposing components to the paper api wherever mojang uses them.
If I missed anything, please add them as comment below so I can add them.

- [ ] chat event
- [x] chat message (already in paper api, Player#sendMessage(BaseComponent)
- [x] broadcast message (already in paper api, Server#broadcast(BaseComponent)
- [x] title (already in paper api, Player#showTitle + Title class)
- [ ] action bar
- [ ] item display name (https://github.com/PaperMC/Paper/pull/3513)
- [ ] item lore (https://github.com/PaperMC/Paper/pull/3513)
- [ ] entity display name
- [ ] motd
- [ ] books (book content is in BookMeta.spigot(), move up)
- [ ] signs
- [ ] scoreboard stuff
- [ ] tab list header/footer
- [ ] inventory titles
- [ ] kick/ban message
- [ ] boss bar name/title

**Comment by KennyTV** [comment]
Inventory titles, disconnect

**Comment by legofreak1999** [comment]
bossbar?

**Comment by MiniDigger** [comment]
@legofreak1999, thanks, added, please remove your comment now so this stays clean :)

**Comment by zml2008** [comment]
Paper has API for [Title](https://papermc.io/javadocs/paper/1.16/com/destroystokyo/paper/Title.html) and Spigot has API for [Book contents](https://papermc.io/javadocs/paper/1.16/org/bukkit/inventory/meta/BookMeta.Spigot.html#addPage-net.md_5.bungee.api.chat.BaseComponent:A...-) but not title and author

**Comment by MiniDigger** [comment]
@zml2008, thanks, added

**Comment by legofreak1999** [comment]
might be wrong but seems like the tab list head and footer also have been covered in the same title class

[Tab List](https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/Player.html#setPlayerListHeaderFooter-net.md_5.bungee.api.chat.BaseComponent-net.md_5.bungee.api.chat.BaseComponent-)

[Title class/patch](https://github.com/PaperMC/Paper/blob/master/Spigot-API-Patches/0016-Player-Tab-List-and-Title-APIs.patch)

**Comment by CadyKing** [comment]
All the ban and kick methods and Player take strings so those also need to be updated

**Comment by kashike** [comment]
#4830
