### ISSUE TITLE
1.18 update tracking issue

### ISSUE THREAD

**Issue by Proximyst** [PaperMC/Paper#6136]
This acts as a tracker for what we will need to do on the 1.18 update, with regards to changes such as deprecations.

Tasks may be added by any PaperMC member with write (because triage obviously wouldn't need access to triage things...).

**Comment by jpenilla** [comment]
~~These issues have been fixed by Mojang and Paper's fixes for them are no longer needed.
MC-187716
MC-29274: The wither now targets EntityLiving instead of EntityInsentient.~~

see https://github.com/PaperMC/Paper/pull/6927

edit: has been addressed d347f169

**Comment by kennytv** [comment]
After no tick, only this one is left:
- Optimize-sending-packets-to-nearby-locations-sounds-

~~Incremental chunk saving should also be a fairly easy port now if actually wanted~~

**Comment by MiniDigger** [comment]
~~dropped anti-xray for now (the patch in removed already has changes by me!) since it needs more work~~

**Comment by kennytv** [comment]
~~Bukkit's `LegacyTest.toLegacyMaterial` fails because of DataConverter~~

**Comment by kennytv** [comment]
~~Check if `0432-Optimize-isOutsideRange-to-use-distance-maps` performance improvement is still high enough to warrant the high-diff patch (Mojang improved the method, also now being `anyPlayerCloseEnoughForSpawning`)~~ Vanilla is good now

**Comment by kennytv** [comment]
~~`0801-Configurable-feature-seeds` only... kind of works? (see https://i.imgur.com/w19ryK1.jpeg and https://i.imgur.com/YjeoefU.jpeg)
Also, quadruple check if seed based feature search is actually needed, since Vanilla is pretty fast with that now~~
fixed

**Comment by kennytv** [comment]
~~improve incremental chunk saving, probably? (lastSaveTime long in LevelChunk, save method)~~

**Comment by Machine-Maker** [comment]
### Updated TODO

- [x] Allow delegation to vanilla chunk gen (Server/API)
- [x] Generator Settings patch #6960 (only flat bedrock, should probably be renamed as such since most of the settings were removed a while ago)
- [x] ~~No tick view distance~~ (mojang added simulation distance)
- [ ] Optimise TickListServer
- [x] ~~Optimise sending packets to nearby locations~~ should be dropped
- [x] Optimize WorldBorder collision checks and air https://github.com/PaperMC/Paper/pull/7368
- [x] ~~Optimize NibbleArray to use pooled buffers~~ (dropped, conflicts with Starlight)
- [x] ~~Fix incorrect status dataconverter for pre 1.13 chunks~~ ___(~~still needed with DataConverter?~~ Nope, not needed)___
- [x] Highly optimise single and multi-AABB VoxelShapes and collisions
- [x] Optimise chunk tick iteration #6950
- [x] Replace player chunk loader system https://github.com/PaperMC/Paper/pull/7368
**needs:** *No tick view distance*
- [x] Replace ticket level propagator https://github.com/PaperMC/Paper/pull/7368
**needs:** *Replace player chunk loader system*
- [x] Optimise collision checking in player move packet handling 
**needs:** *Highly optimise single and multi-AABB VoxelShapes and collisions*
- [x] Fix Codec log spam ___(~~still needed with DataConverter?~~ Yes, is needed)___
- [ ] Cache palette array
